create table category(
	id int generated by default as identity(start with 1) primary key,
	name varchar (20) not null unique
);

create table product(
	id int primary key generated by default as identity(start with 1),
	name varchar(20) not null ,
	category_id int not null,
	price int,
	foreign key(category_id) references category(id)
);
